import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { EXIT_ERROR, EXIT_OK } from "../src/cli.js";
import { ObservationStore } from "../src/memory/observations.js";
import { makeRepo, run, write } from "./helpers.js";

function initialized(): string {
  const repo = makeRepo();
  run(repo, ["init", "--tools", "agents"]);
  write(repo, ".env.example", "KAFKA_BOOTSTRAP_SERVERS=localhost:9092\n");
  return repo;
}

const observationsDir = (repo: string) => join(repo, ".openax", "observations");
const count = (repo: string) => (existsSync(observationsDir(repo)) ? readdirSync(observationsDir(repo)).filter((f) => f.endsWith(".md")).length : 0);

const KAFKA = [
  "observe", "--kind", "ambiguity",
  "--title", "Kafka configured but unused",
  "--statement", "It appears Kafka is configured but no code uses it.",
  "--question", "Is Kafka leftover or planned?",
  "--evidence", ".env.example",
];

describe("openax observe", () => {
  it("records an observation with evidence", () => {
    const repo = initialized();
    const r = run(repo, [...KAFKA, "--evidence", "./app.py"]);
    expect(r.code).toBe(EXIT_OK);
    expect(r.out).toContain("Observed OBS-0001: Kafka configured but unused\n  .openax/observations/OBS-0001-kafka-configured-but-unused.md");
    const [o] = new ObservationStore(observationsDir(repo)).all();
    expect(o).toMatchObject({ kind: "ambiguity", status: "open", evidence: [".env.example", "app.py"], question: "Is Kafka leftover or planned?" });

    run(repo, ["observe", "--kind", "component", "--title", "API", "--statement", "An HTTP API.", "--evidence", "app.py"]);
    expect(new ObservationStore(observationsDir(repo)).all().map((x) => x.id)).toEqual(["OBS-0001", "OBS-0002"]);
  });

  it("rejects invalid input and writes nothing", () => {
    const repo = initialized();
    const cases: [string[], string][] = [
      [KAFKA.map((a) => (a === "ambiguity" ? "rumour" : a)), "--kind, one of"],
      [KAFKA.filter((_, i) => i !== 3 && i !== 4), "--title"],
      [KAFKA.filter((_, i) => i !== 5 && i !== 6), "--statement"],
      [KAFKA.filter((_, i) => i !== 7 && i !== 8), "needs --question"],
      [KAFKA.slice(0, 9), "at least one --evidence"],
      [[...KAFKA, "--evidence", "app/does_not_exist.py"], "`app/does_not_exist.py` does not exist"],
      [[...KAFKA, "--evidence", "../outside.txt"], "does not exist in this repository"],
      [[...KAFKA, "--evidence", "/etc/hosts"], "does not exist in this repository"],
    ];
    for (const [argv, message] of cases) {
      const r = run(repo, argv);
      expect(r.code, message).toBe(EXIT_ERROR);
      expect(r.err, message).toContain(message);
    }
    expect(count(repo)).toBe(0);
  });
});

describe("project overview and resolving ambiguities", () => {
  const readProject = (repo: string) => readFileSync(join(repo, ".openax", "project.md"), "utf8");
  const decide = (extra: string[]) => ["record", "--title", "Kafka is planned", "--decision", "Kafka is reserved for future events.", "--why", "Мы планируем события в Kafka.", ...extra];

  it("regenerates project.md on observe and on record --resolves", () => {
    const repo = initialized();
    run(repo, KAFKA);
    run(repo, ["observe", "--kind", "datastore", "--title", "PostgreSQL", "--statement", "It appears PostgreSQL is the main database.", "--evidence", "app.py"]);

    let text = readProject(repo);
    expect(text).toContain("Generated by OpenAX");
    expect(text).toContain("## Open questions\n\n- [OBS-0001: Kafka configured but unused](observations/OBS-0001-kafka-configured-but-unused.md) — Is Kafka leftover or planned?");
    expect(text).toContain("## Data stores\n\n- [OBS-0002: PostgreSQL](observations/OBS-0002-postgresql.md) — It appears PostgreSQL is the main database.");

    const r = run(repo, decide(["--resolves", "OBS-0001"]));
    expect(r.code).toBe(EXIT_OK);
    expect(r.out).toContain("OBS-0001 resolved by DEC-0001");
    const decision = readFileSync(join(repo, ".openax", "decisions", "DEC-0001-kafka-is-planned.md"), "utf8");
    expect(decision).toContain("resolves: [OBS-0001]");
    expect(decision).toContain("## Why\nМы планируем события в Kafka.");

    const obs = new ObservationStore(observationsDir(repo)).get("OBS-0001")!;
    expect(obs).toMatchObject({ status: "resolved", resolvedBy: "DEC-0001", statement: "It appears Kafka is configured but no code uses it." });
    text = readProject(repo);
    expect(text).not.toContain("## Open questions");
    expect(text).toContain("## Resolved questions\n\n- [OBS-0001: Kafka configured but unused](observations/OBS-0001-kafka-configured-but-unused.md) — answered in DEC-0001");
  });

  it("validates --resolves before writing anything", () => {
    const repo = initialized();
    run(repo, KAFKA);
    run(repo, ["observe", "--kind", "component", "--title", "API", "--statement", "An HTTP API.", "--evidence", "app.py"]);
    const decisions = () => readdirSync(join(repo, ".openax", "decisions")).filter((f) => f.endsWith(".md"));

    expect(run(repo, decide(["--resolves", "OBS-0099"])).err).toContain("Unknown observation OBS-0099");
    expect(run(repo, decide(["--resolves", "OBS-0002"])).err).toContain("OBS-0002 is a component observation, not an open question");
    expect(decisions()).toEqual([]);

    expect(run(repo, decide(["--resolves", "OBS-0001"])).code).toBe(EXIT_OK);
    expect(run(repo, decide(["--resolves", "OBS-0001"])).err).toContain("OBS-0001 is already resolved by DEC-0001");
    expect(decisions()).toHaveLength(1);
  });
});

describe("openax decisions --observations", () => {
  it("lists open observations, and resolved ones with --all", () => {
    const repo = initialized();
    expect(run(repo, ["decisions", "--observations"]).out).toBe("No open observations.");
    run(repo, KAFKA);
    run(repo, ["observe", "--kind", "ambiguity", "--title", "Two email senders", "--statement", "Resend and SMTP both appear.", "--question", "Which one?", "--evidence", "app.py"]);
    run(repo, ["record", "--title", "Resend for email", "--decision", "Email goes through Resend.", "--why", "SMTP was a fallback we removed.", "--resolves", "OBS-0002"]);

    let r = run(repo, ["decisions", "--observations"]);
    expect(r.out).toBe("OBSERVED\nOBS-0001  ambiguity    Kafka configured but unused  [open]");
    r = run(repo, ["decisions", "--observations", "--all", "-v"]);
    expect(r.out).toContain("OBS-0002  ambiguity    Two email senders  [resolved by DEC-0001]");
    expect(r.out).toContain("          Question: Which one?\n          Evidence: app.py");
    expect(run(repo, ["decisions"]).out).toContain("DECIDED\nDEC-0001");
  });

  it("labels decisions as DECIDED in packets", () => {
    const repo = initialized();
    write(repo, "worker.py", "import celery\n");
    expect(run(repo, ["check"]).out).toContain("## DECIDED: recorded decisions\n\nNone yet.");
  });
});
