/** scenario "<name>" and describe: generated on demand, never stored (DEC-0011, design §13). */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { EXIT_OK } from "../src/cli.js";
import { monorepo, put } from "./fixtures.js";
import { run } from "./helpers.js";

function described(): string {
  const repo = monorepo();
  run(repo, ["init", "--tools", "agents"]);
  run(repo, ["onboard"]);
  run(repo, ["model", "set", "SYS-0001", "--name", "Pagey", "--purpose", "Landing pages for small businesses."]);
  run(repo, ["model", "set", "transactions", "--purpose", "Sells plans."]);
  run(repo, ["model", "relate", "transactions", "Resend", "--kind", "calls", "--description", "receipts"]);
  run(repo, ["scenario", "add", "--name", "Buying a plan", "--entry", "route:POST /v1/transactions/plan", "--description", "A user pays for a plan."]);
  run(repo, ["model", "set", "transactions", "--scenario", "Buying a plan"]);
  return repo;
}

describe("openax scenario <name>", () => {
  it("prints the scenario, its entry point, the tagged elements and the sequence-diagram instructions", () => {
    const repo = described();
    const r = run(repo, ["scenario", "buying a plan"]);
    expect(r.code).toBe(EXIT_OK);
    expect(r.out).toContain("# OpenAX scenario: Buying a plan (SCN-0001)");
    expect(r.out).toContain("Draw a Mermaid `sequenceDiagram`");
    expect(r.out).toContain("Nothing is stored");
    expect(r.out).toContain("## Scenario\n\nA user pays for a plan.\n\nEntry point: route:POST /v1/transactions/plan\nSource: .openax/scenarios/SCN-0001-buying-a-plan.md");
    expect(r.out).toContain("### CMP-0005: transactions [component in api, described]");
    expect(r.out).toContain("-> calls EXT-0001: receipts");
    expect(r.out).toContain("Evidence: backend/app/api/v1/billing.py");
    expect(run(repo, ["scenario", "SCN-0001"]).out).toContain("# OpenAX scenario: Buying a plan");
    const json = JSON.parse(run(repo, ["scenario", "SCN-0001", "--json"]).out);
    expect(json.scenario).toMatchObject({ id: "SCN-0001", entry: "route:POST /v1/transactions/plan" });
    expect(json.elements[0].id).toBe("CMP-0005");
    expect(run(repo, ["scenario", "checkout"]).err).toContain('Unknown scenario "checkout". Known: SCN-0001 Buying a plan.');
    run(repo, ["scenario", "add", "--name", "Empty"]);
    expect(run(repo, ["scenario", "Empty"]).out).toContain("None yet: tag them with `npx @openax/cli model set <id> --scenario SCN-0002`");
  });
});

describe("openax describe", () => {
  it("hands the agent the generated overview and the writing rules", () => {
    const repo = described();
    const r = run(repo, ["describe"]);
    expect(r.code).toBe(EXIT_OK);
    expect(r.out).toContain("# OpenAX describe");
    expect(r.out).toContain("Start from the system's purpose");
    expect(r.out).toContain("## The model (generated project.md)\n\n<!-- Generated by OpenAX");
    expect(r.out).toContain("# Pagey\n\nLanding pages for small businesses.");
    expect(r.out).toContain("- [SCN-0001: Buying a plan](scenarios/SCN-0001-buying-a-plan.md) — A user pays for a plan.");
    const json = JSON.parse(run(repo, ["describe", "--json"]).out);
    expect(json.readme_markers).toEqual(["<!-- openax:describe:start -->", "<!-- openax:describe:end -->"]);
    expect(json.overview).toContain("# Pagey");
  });

  it("inserts and replaces the description in README between markers", () => {
    const repo = described();
    put(repo, "docs/description.md", "Pagey builds landing pages.\n\nIt has an API and a web app.\n");
    const first = run(repo, ["describe", "--write-readme", "docs/description.md"]);
    expect(first.code).toBe(EXIT_OK);
    expect(first.out).toContain("README.md: description added");
    const readme = readFileSync(join(repo, "README.md"), "utf8");
    expect(readme).toBe("# Pagey\n\n<!-- openax:describe:start -->\nPagey builds landing pages.\n\nIt has an API and a web app.\n<!-- openax:describe:end -->\n");

    writeFileSync(join(repo, "README.md"), "intro\n\n<!-- openax:describe:start -->\nold\n<!-- openax:describe:end -->\n\n## Contributing\n");
    put(repo, "docs/description.md", "New text.\n");
    expect(run(repo, ["describe", "--write-readme", "docs/description.md"]).out).toContain("description replaced");
    expect(readFileSync(join(repo, "README.md"), "utf8")).toBe("intro\n\n<!-- openax:describe:start -->\nNew text.\n<!-- openax:describe:end -->\n\n## Contributing\n");
    expect(run(repo, ["describe", "--write-readme", "nope.md"]).err).toContain("File nope.md not found");
  });

  it("needs a model", () => {
    const repo = monorepo();
    run(repo, ["init", "--tools", "agents"]);
    expect(run(repo, ["describe"]).err).toContain("The model is empty");
  });
});
