/** `.openax/project.md`: a readable overview generated from the whole memory. Never edited by hand. */

import { writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { isActive, isInferred, type Decision } from "./decisions.js";
import { isContainer, type Element } from "./model.js";
import type { Kind, Observation } from "./observations.js";
import { isOpenQuestion, byValue, type Question } from "./questions.js";
import { formatEntry, type Scenario } from "./scenarios.js";

export const PROJECT_FILE = "project.md";

export interface Memory {
  elements: Element[];
  scenarios: Scenario[];
  questions: Question[];
  decisions: Decision[];
  observations: Observation[];
}

const OBSERVATION_SECTIONS: [Kind, string][] = [
  ["component", "Components"],
  ["datastore", "Data stores"],
  ["integration", "External integrations"],
  ["mechanism", "Mechanisms"],
  ["smell", "Smells"],
];

const file = (dir: string, path: string | null, id: string) => `${dir}/${path ? basename(path) : `${id}.md`}`;
const elementLink = (e: Element) => `[${e.id}](${file("model", e.path, e.id)})`;
const obsLink = (o: Observation) => `[${o.id}: ${o.title}](${file("observations", o.path, o.id)})`;
const decLink = (d: Decision) => `[${d.id}: ${d.title}](${file("decisions", d.path, d.id)})`;
const qLink = (q: Question) => `[${q.id}](${file("questions", q.path, q.id)})`;
const scnLink = (s: Scenario) => `[${s.id}: ${s.name}](${file("scenarios", s.path, s.id)})`;

function describe(e: Element): string {
  const tech = e.technology ? ` (${e.technology})` : "";
  const purpose = e.purpose ? ` — ${e.purpose.split("\n")[0]}` : e.status === "observed" ? " — *not described yet*" : "";
  return `**${e.name}**${tech}${purpose} ${elementLink(e)}`;
}

function counts(elements: Element[]): string {
  const by = (status: string) => elements.filter((e) => e.status === status).length;
  return `${elements.length} elements: ${by("observed")} observed, ${by("described")} described, ${by("confirmed")} confirmed`;
}

export function renderProject(memory: Memory): string {
  const { elements, scenarios, questions, decisions, observations } = memory;
  const system = elements.find((e) => e.kind === "system");
  const parts = [
    "<!-- Generated by OpenAX from .openax/model, scenarios, questions, decisions and observations. Do not edit this file: edit those files or use the openax commands instead. -->",
    `# ${system?.name ?? "Project overview"}`,
  ];

  if (elements.length === 0 && observations.length === 0) {
    parts.push("Nothing observed yet. Ask your coding agent to run `openax onboard`.");
  } else if (system?.purpose) {
    parts.push(system.purpose);
  } else {
    parts.push("*System purpose not recorded yet.* The first onboarding question asks for it.");
  }
  if (elements.length) parts.push(`Model status: ${counts(elements)}.`);

  const containers = elements.filter(isContainer);
  if (containers.length) {
    const lines: string[] = [];
    for (const c of containers) {
      lines.push(`- ${describe(c)}${c.kind === "library" ? " [library]" : ""}`);
      for (const comp of elements.filter((e) => e.parent === c.id)) {
        const scn = comp.scenarios.length ? ` [${comp.scenarios.join(", ")}]` : "";
        lines.push(`  - ${describe(comp)}${scn}`);
      }
    }
    parts.push(`## Containers\n\n${lines.join("\n")}`);
  }
  const orphans = elements.filter((e) => e.kind === "component" && !containers.some((c) => c.id === e.parent));
  if (orphans.length) parts.push(`## Components without a container\n\n${orphans.map((e) => `- ${describe(e)}`).join("\n")}`);

  const externals = elements.filter((e) => e.kind === "external");
  if (externals.length) parts.push(`## External systems\n\n${externals.map((e) => `- ${describe(e)}`).join("\n")}`);
  const persons = elements.filter((e) => e.kind === "person");
  if (persons.length) parts.push(`## People\n\n${persons.map((e) => `- ${describe(e)}`).join("\n")}`);

  if (scenarios.length) {
    const lines = scenarios.map((s) => {
      const impl = elements.filter((e) => e.scenarios.includes(s.id)).map((e) => e.name);
      const entry = s.entry ? ` Entry: \`${formatEntry(s.entry)}\`.` : "";
      const by = impl.length ? ` Implemented by: ${impl.join(", ")}.` : " *No element tagged yet.*";
      return `- ${scnLink(s)}${s.description ? ` — ${s.description}` : ""}${entry}${by}`;
    });
    parts.push(`## Scenarios\n\n${lines.join("\n")}`);
  }

  const active = decisions.filter(isActive);
  if (active.length) parts.push(`## Decisions (DECIDED)\n\n${active.map((d) => `- ${decLink(d)}`).join("\n")}`);
  const inferred = decisions.filter(isInferred);
  if (inferred.length) {
    parts.push(
      `## Inferred decisions (derived from history, not confirmed)\n\n${inferred.map((d) => `- ${decLink(d)}${d.source ? ` — source: ${d.source}` : ""}`).join("\n")}\n\nConfirm or reject them with \`openax decisions --inferred\`.`,
    );
  }

  const openQuestions = questions.filter(isOpenQuestion).sort(byValue);
  const ambiguities = observations.filter((o) => o.kind === "ambiguity");
  const openAmbiguities = ambiguities.filter((o) => o.status === "open");
  if (openQuestions.length || openAmbiguities.length) {
    const lines = [
      ...openQuestions.map((q) => `- ${qLink(q)} — ${q.text.split("\n")[0]}${q.elements.length ? ` (${q.elements.join(", ")})` : ""}`),
      ...openAmbiguities.map((o) => `- ${obsLink(o)} — ${o.question || o.statement}`),
    ];
    parts.push(`## Open questions\n\n${lines.join("\n")}`);
  }

  for (const [kind, heading] of OBSERVATION_SECTIONS) {
    const list = observations.filter((o) => o.kind === kind);
    if (list.length) parts.push(`## ${heading} (OBSERVED)\n\n${list.map((o) => `- ${obsLink(o)}${o.statement ? ` — ${o.statement}` : ""}`).join("\n")}`);
  }

  const answered = questions.filter((q) => q.status === "answered");
  const resolved = ambiguities.filter((o) => o.status === "resolved");
  if (answered.length || resolved.length) {
    const lines = [
      ...answered.map((q) => `- ${qLink(q)} — ${q.text.split("\n")[0]} → ${q.answer.split("\n")[0]}${q.answeredBy && q.answeredBy !== "owner" ? ` (${q.answeredBy})` : ""}`),
      ...resolved.map((o) => `- ${obsLink(o)} — answered in ${o.resolvedBy || "a decision"}`),
    ];
    parts.push(`## Answered questions\n\n${lines.join("\n")}`);
  }
  return parts.join("\n\n") + "\n";
}

/** Rewrite the overview; `openaxDir` is the `.openax/` directory. */
export function writeProject(openaxDir: string, memory: Memory): string {
  const path = join(openaxDir, PROJECT_FILE);
  writeFileSync(path, renderProject(memory), "utf8");
  return path;
}
