/** `.openax/project.md`: a readable overview generated from observations. Never edited by hand. */

import { writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import type { Kind, Observation } from "./observations.js";

export const PROJECT_FILE = "project.md";

const SECTIONS: [Kind, string][] = [
  ["component", "Components"],
  ["datastore", "Data stores"],
  ["integration", "External integrations"],
  ["mechanism", "Mechanisms"],
];

const link = (o: Observation) => `[${o.id}: ${o.title}](observations/${o.path ? basename(o.path) : `${o.id}.md`})`;

export function renderProject(observations: Observation[]): string {
  const parts = [
    "<!-- Generated by OpenAX from .openax/observations/. Do not edit this file: edit the observation files instead. -->",
    "# Project overview (OBSERVED)",
    "What OpenAX and the coding agent found in this repository. These are observations, not decisions: " +
      "`.openax/decisions/` holds what the developer decided.",
  ];
  const ambiguities = observations.filter((o) => o.kind === "ambiguity");
  const open = ambiguities.filter((o) => o.status === "open");
  const resolved = ambiguities.filter((o) => o.status === "resolved");

  if (observations.length === 0) parts.push("Nothing observed yet. Ask your coding agent to run `openax onboard`.");
  if (open.length) parts.push(`## Open questions\n\n${open.map((o) => `- ${link(o)} — ${o.question || o.statement}`).join("\n")}`);
  for (const [kind, heading] of SECTIONS) {
    const list = observations.filter((o) => o.kind === kind);
    if (list.length) parts.push(`## ${heading}\n\n${list.map((o) => `- ${link(o)}${o.statement ? ` — ${o.statement}` : ""}`).join("\n")}`);
  }
  if (resolved.length) {
    parts.push(`## Resolved questions\n\n${resolved.map((o) => `- ${link(o)} — answered in ${o.resolvedBy || "a decision"}`).join("\n")}`);
  }
  return parts.join("\n\n") + "\n";
}

/** Rewrite the overview; `openaxDir` is the `.openax/` directory. */
export function writeProject(openaxDir: string, observations: Observation[]): string {
  const path = join(openaxDir, PROJECT_FILE);
  writeFileSync(path, renderProject(observations), "utf8");
  return path;
}
